<a href="https://colab.research.google.com/github/AVI18794/Pytorch_Tuts/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch Basics: Tensors & Gradients

In [1]:
# !pip install torch

In [2]:
import torch

#Tensors

In [4]:
#Tensors:A tensor is a number , vector, matrix or any n dimensional array.
#Lets create a tensor with a single number
tensor1 = torch.tensor(4.)
tensor1

tensor(4.)

In [5]:
#Check the data type of the tensor
tensor1.dtype

torch.float32

In [6]:
#Vector
t2 = torch.tensor([1,2,3,4.])
t2

tensor([1., 2., 3., 4.])

In [7]:
t2.dtype

torch.float32

In [9]:
#Matrix
t3 = torch.tensor([[1,2],[3,4],[5,6]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
#3 Dimensional Array
t4 = torch.tensor([
                   [[11,12,13],
                    [14,15,16]],
                   [[17,18,19],
                    [20,21,22]]
                   
])

t4

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])

In [11]:
t4.dtype

torch.int64

In [19]:
#Check the shape of the tensors
print(tensor1)
tensor1.shape

tensor(4.)


torch.Size([])

In [20]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [21]:
print(t3)
t3.shape

tensor([[1, 2],
        [3, 4],
        [5, 6]])


torch.Size([3, 2])

In [22]:
print(t4)
t4.shape# A tensor of shape 2,2,3  which is nothing but the 2 tensor(matrix) of shape 2,3

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])


torch.Size([2, 2, 3])

# Tensor Operations and Gradients

In [24]:
#Creating tensors
x = torch.tensor(3.)
w= torch.tensor(4.,requires_grad = True)
b = torch.tensor(5.,requires_grad=True)


In [25]:
#Arithmetic operations
y = w*x+b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [26]:
#Compute the derivates
y.backward()

In [27]:
#Display the gradients
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)
