<a href="https://colab.research.google.com/github/AVI18794/Pytorch_Tuts/blob/main/Pytorch_2_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
#Input(temp,rainfall,humidity)
inputs = np.array([[73,67,43],
                   [91,88,76],
                   [98,78,67],
                   [78,56,43],
                   [89,67,78]],dtype='float32')


In [4]:
#Targets(apples,oranges)
targets = np.array([[73,67],
                   [91,88],
                   [98,78],
                   [78,87],
                   [89,76]],dtype='float32')

In [5]:
#Convert the inputs and outputs into tensors
inputs= torch.from_numpy(inputs)
output = torch.from_numpy(targets)

In [6]:
print(inputs)
print(output)

tensor([[73., 67., 43.],
        [91., 88., 76.],
        [98., 78., 67.],
        [78., 56., 43.],
        [89., 67., 78.]])
tensor([[73., 67.],
        [91., 88.],
        [98., 78.],
        [78., 87.],
        [89., 76.]])


#Build a model (Linear Regression)

In [7]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.0517,  0.8535,  0.2147],
        [-0.3076, -0.5879, -0.6972]], requires_grad=True)
tensor([-1.3136,  0.0366], requires_grad=True)


In [8]:
def model(x):
  return x @ w.t() + b


In [9]:
#Generate predictions
preds = model(inputs)
print(preds)

tensor([[  68.8728,  -91.7907],
        [  94.8102, -132.6831],
        [  84.7053, -122.6816],
        [  59.7431,  -86.8613],
        [  77.2134, -121.1155]], grad_fn=<AddBackward0>)


In [10]:
#Compare it with target
print(output)

tensor([[73., 67.],
        [91., 88.],
        [98., 78.],
        [78., 87.],
        [89., 76.]])


In [11]:
#Compare the model performance
def MSE(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [12]:
#Compute the loss
loss = MSE(preds,output)
print(loss)

tensor(18395.1445, grad_fn=<DivBackward0>)


In [13]:
#Compute the gradients
loss.backward()

In [14]:
#Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.0517,  0.8535,  0.2147],
        [-0.3076, -0.5879, -0.6972]], requires_grad=True)
tensor([[  -746.0967,   -558.0599,   -496.6082],
        [-16489.0273, -13731.0449, -11979.3262]])


In [15]:
print(b)
print(b.grad)

tensor([-1.3136,  0.0366], requires_grad=True)
tensor([  -8.7310, -190.2264])


In [16]:
#Adjust the weights and reset_gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [17]:
#now take a look at the new wights and bias
print(w)
print(b)

tensor([[ 0.0591,  0.8590,  0.2196],
        [-0.1427, -0.4506, -0.5774]], requires_grad=True)
tensor([-1.3135,  0.0385], requires_grad=True)


In [19]:
#calculat4e the loss
pred = model(inputs)
loss=MSE(pred,output)
print(loss)

tensor(12844.0742, grad_fn=<DivBackward0>)


In [27]:
#Train for multiple epochs
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MSE(preds, output)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
 
 
