<a href="https://colab.research.google.com/github/AVI18794/Pytorch_Tuts/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch Basics: Tensors & Gradients

In [1]:
# !pip install torch

In [2]:
import torch

#Tensors

In [4]:
#Tensors:A tensor is a number , vector, matrix or any n dimensional array.
#Lets create a tensor with a single number
tensor1 = torch.tensor(4.)
tensor1

tensor(4.)

In [5]:
#Check the data type of the tensor
tensor1.dtype

torch.float32

In [6]:
#Vector
t2 = torch.tensor([1,2,3,4.])
t2

tensor([1., 2., 3., 4.])

In [7]:
t2.dtype

torch.float32

In [9]:
#Matrix
t3 = torch.tensor([[1,2],[3,4],[5,6]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
#3 Dimensional Array
t4 = torch.tensor([
                   [[11,12,13],
                    [14,15,16]],
                   [[17,18,19],
                    [20,21,22]]
                   
])

t4

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])

In [11]:
t4.dtype

torch.int64

In [14]:
#Check the shape of the tensors
tensor1.shape

torch.Size([])

In [15]:
t2.shape

torch.Size([4])

In [16]:
t3.shape

torch.Size([3, 2])

In [18]:
t4.shape# A tensor of shape 2,2,3  which is nothing but the 2 tensor(matrix) of shape 2,3

torch.Size([2, 2, 3])